#!/usr/bin/env bash

# This script compares all pihole adlists and outputs any lists that are redundant
# (contain no unique domains)

# Get a list of all adlists
adlists=(/etc/pihole/adlists.list/*)

# Create a dictionary to keep track of the unique domains in each adlist
declare -A unique_domains

# For each adlist, read in the domains and add them to the dictionary
for adlist in "${adlists[@]}"; do
  while read -r domain; do
    # If this is the first time we've seen this domain, initialize an empty
    # array to hold the adlists that contain it
    if [[ ! ${unique_domains[$domain]} ]]; then
      unique_domains[$domain]=()
    fi

    # Add this adlist to the list of adlists that contain this domain
    unique_domains[$domain]+=($adlist)
  done < $adlist
done

# Go through the dictionary and print any adlists that have no unique domains
for domain in "${!unique_domains[@]}"; do
  # If this domain appears in more than one adlist, those adlists are redundant
  if (( ${#unique_domains[$domain]} > 1 )); then
    echo "The following adlists are redundant:"
    printf '%s\n' "${unique_domains[$domain]}"
  fi
done
