#!/usr/bin/env python

# This script compares all pihole adlists and outputs any lists that are redundant
# (contain no unique domains)

import os

# First, get a list of all adlists
adlists = os.listdir("/etc/pihole/adlists.list")

# Next, create a dictionary to keep track of the unique domains in each adlist
unique_domains = {}

# For each adlist, read in the domains and add them to the dictionary
for adlist in adlists:
  with open("/etc/pihole/adlists.list/" + adlist) as f:
    for line in f:
      domain = line.strip()
      if domain not in unique_domains:
        unique_domains[domain] = []
      unique_domains[domain].append(adlist)

# Finally, go through the dictionary and print any adlists that have no unique domains
for domain, adlists in unique_domains.items():
  if len(adlists) > 1:
    print("The following adlists are redundant:")
    print(", ".join(adlists))
