#!/bin/bash

# Iteriere über alle Adlisten
for adlist in $(ls /etc/pihole/adlists.list)
do
  # Vergleiche jede Adliste mit der Datenbank
  unique_domains=$(comm -23 <(sort $adlist) <(sort /etc/pihole/gravity.db))
  # Wenn die Anzahl der einzigartigen Domänen 0 ist, gebe die Adliste aus
  if [ $(echo $unique_domains | wc -w) -eq 0 ]
  then
    echo $adlist
  fi
done
